pipeline {
    agent {
        node {
            label 'my-maven'
            customWorkspace '/home/mysoft/maven/apache-maven-3.6.3'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -vesion'
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Install') {
            steps {
                sh 'mvn install'
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
